// ---------------- HELP & GUIDE CONTENT ----------------
// Structured, data-only source for the in-app Help & Guide screen (src/components/
// HelpGuideScreen.jsx) — deliberately kept out of App.jsx and out of the screen component
// itself so an app update (a renamed feature, a newly-shipped screen, a copy fix) never touches
// navigation logic, only this file. This is also the single source of truth the downloadable
// PDF (public/docs/BRK_Lift_User_Guide_v1.pdf, generated by scripts/generateUserGuidePdf.mjs)
// is built from — update an article here and both the in-app copy and a regenerated PDF stay
// in sync.
//
// Every article's `content` is a small list of typed blocks the screen renders generically:
//   { type: "p", text }                    — a paragraph
//   { type: "h", text }                    — a sub-heading within the article
//   { type: "list", items: [string] }      — a plain bullet list
//   { type: "steps", items: [string] }     — a numbered sequence
//   { type: "terms", items: [{term, def}] } — a glossary block
//   { type: "qa", items: [{q, a}] }        — one or more question/answer pairs
//   { type: "callout", text }              — a single highlighted one-liner
// Adding a new block type only ever means one more `case` in the renderer — never a change to
// how sections are listed, searched, or navigated.
//
// `keywords` feed the Help screen's search box (title + keywords, nothing fancier — task:
// "do not build a complex search backend").

export const HELP_SECTIONS = [
  {
    id: "quickStart",
    title: "Quick Start",
    keywords: ["start", "first workout", "getting started", "new user", "onboarding"],
    summary: "The basic loop — what to do, in order.",
    content: [
      {
        type: "steps",
        items: [
          "Open Today — it's the home screen, and it always shows what's next.",
          "Log today's bodyweight if you want to (tap the [+] on the Bodyweight tile) — totally optional, any day you skip it just shows as a gap in your trend.",
          "Check Readiness if you're tracking it — a quick sleep/soreness/motivation check-in that can nudge your suggested working weight.",
          "Tap Start on today's workout, or Swap Workout if you'd rather train something else today.",
          "Log actual sets as you go — weight, reps, and RIR (or RPE) for each one. What you log is what gets saved to history, PRs, and progression.",
          "Change anything reality doesn't match the plan — swap an exercise, switch equipment, remove one, or reorder — none of it touches your saved program.",
          "Finish Workout when you're done — it shows a quick summary first (exercises, sets, time) so nothing finishes by accident.",
          "Review your recap — a shareable card, or a Full Recap with every set, right after finishing.",
          "Come back anytime through Train > History to see exactly what you did on any past day.",
          "Watch Progress build up over time from the sessions you've actually logged — no manual entry needed.",
        ],
      },
      { type: "callout", text: "None of these steps are required in a strict order — Today always tells you what's next." },
    ],
  },

  {
    id: "today",
    title: "Today",
    keywords: ["today", "home", "dashboard", "resume workout", "quick actions"],
    summary: "What the home screen shows and why.",
    content: [
      { type: "p", text: "Today is the app's home screen — it's built to answer \"what do I do right now?\" in one glance, without digging." },
      {
        type: "list",
        items: [
          "Your workout for today — resume it if one's in progress, or start/swap it if not.",
          "Bodyweight — your latest entry and a one-tap [+] to log today's without leaving the screen.",
          "Nutrition — a compact snapshot of today's targets.",
          "Coach Brief — a short note from Coach about your training, when there's something worth surfacing.",
          "Readiness — if you're tracking it, a quick daily check-in.",
          "Quick Actions and a \"More Today\" sheet for anything that doesn't need to live on the main screen every day (this week's schedule, your active Mission, a recent win).",
        ],
      },
      { type: "p", text: "If today is a rest or recovery day, Today reflects that instead of pushing you to train." },
    ],
  },

  {
    id: "training",
    title: "Training",
    keywords: [
      "training", "active workout", "log workout", "sets", "reps", "rir", "rpe", "warmup", "warm-up",
      "working set", "top set", "backoff", "back-off", "drop set", "failure", "amrap", "set quality",
      "notes", "finish exercise", "finish workout", "reopen workout", "clean", "grind", "form breakdown", "pain",
    ],
    summary: "What every logging term means, and the difference between your plan and your session.",
    content: [
      {
        type: "callout",
        text: "PROGRAM = TARGET. SESSION = REALITY. Log what actually happened, not what the plan says should have happened.",
      },
      { type: "h", text: "Set fields" },
      {
        type: "terms",
        items: [
          { term: "Weight", def: "The load on the bar/machine for that set." },
          { term: "Reps", def: "How many reps you actually completed at that weight." },
          { term: "RIR", def: "Reps In Reserve — how many more reps you could have done before failure. Lower means harder. Settings can switch this to RPE (Rate of Perceived Exertion, 6–10 scale) instead if you prefer that system." },
        ],
      },
      { type: "h", text: "Set types" },
      {
        type: "terms",
        items: [
          { term: "Warm-up", def: "Doesn't count toward working volume, PRs, or progression — just prep." },
          { term: "Working", def: "A normal counted set — the default type for everything you log." },
          { term: "Top set", def: "Your heaviest set for the exercise that session." },
          { term: "Back-off", def: "A lighter set performed after the top set, usually for extra volume at a manageable load." },
          { term: "Drop set", def: "One set, logged with a drop (or several) to a lighter weight without resting — shown as weight → weight in your history." },
          { term: "Failure", def: "A set taken to the point you couldn't complete another rep with good form." },
          { term: "AMRAP", def: "As Many Reps As Possible — a set with no fixed rep target." },
        ],
      },
      { type: "h", text: "Set quality" },
      {
        type: "terms",
        items: [
          { term: "Clean", def: "The default — good form, no issues." },
          { term: "Grind", def: "You got the reps, but it was a genuine fight for the last one or two." },
          { term: "Form Breakdown", def: "Technique broke down enough that it's worth flagging for next time." },
          { term: "Pain", def: "Something hurt — flag it so it's visible in your history and to Coach, and never silently repeated." },
        ],
      },
      { type: "h", text: "Actions" },
      {
        type: "terms",
        items: [
          { term: "Notes", def: "Per-exercise or per-session free text — anything worth remembering that doesn't fit a number." },
          { term: "Finish exercise now", def: "Ends an exercise early, using only the sets you've already logged for it — useful when you're doing fewer sets than planned on purpose." },
          { term: "Finish workout", def: "Ends the session. Shows a summary first (exercises completed, working sets, elapsed time) and warns you if any exercise still has sets remaining, so it's never one accidental tap away." },
          { term: "Reopen workout", def: "Undoes a just-finished session and puts you right back into it with everything you logged still intact — for when you tap Finish too early or remember one more set." },
        ],
      },
    ],
  },

  {
    id: "programs",
    title: "Programs",
    keywords: ["programs", "templates", "custom workout", "build", "swap workout", "program timeline"],
    summary: "Following, swapping, and building workouts.",
    content: [
      { type: "p", text: "Programs is where saved multi-day training plans live — pick one to follow, and BRK tracks which day comes next automatically as you finish sessions." },
      {
        type: "list",
        items: [
          "Swap Workout — do a different day (or a completely different program) today without changing what's scheduled for next time.",
          "Custom workout — build a one-off session from scratch.",
          "Program Timeline — see your progress through a program's full schedule.",
        ],
      },
      { type: "p", text: "Following a program never locks you in — every session can still be freely edited once you're inside it (see Training)." },
    ],
  },

  {
    id: "workoutHistory",
    title: "Workout History",
    keywords: ["history", "past workouts", "calendar", "exercise history", "last time", "old workouts"],
    summary: "How do I see what I did last time?",
    content: [
      { type: "qa", items: [{ q: "How do I see what I did last time?", a: "Train > History. It opens directly to your most recent sessions — no calendar required, though one's available if you'd rather browse by date." }] },
      {
        type: "terms",
        items: [
          { term: "Train > History", def: "A searchable, filterable list of every completed workout — search by name or exercise, or filter by program or PR sessions." },
          { term: "Calendar", def: "The same history, laid out by date — tap any marked day to see what you did." },
          { term: "Exercise History", def: "From an active exercise (or wherever you're logging one), tap \"View history\" to see every prior time you've done that exact movement." },
          { term: "Equipment-aware history", def: "If you've used more than one machine for an exercise, history keeps them separate by default — a heavier lift on one machine never gets compared against a lighter one on another." },
        ],
      },
      { type: "p", text: "Tapping any past session — from History, the calendar, Today, or Progress — always opens the exact same, exact data for that day. Never a reconstruction." },
    ],
  },

  {
    id: "progress",
    title: "Progress",
    keywords: ["progress", "analytics", "trends", "prs", "volume", "adherence"],
    summary: "Trends, PRs, and where you stand — built from your real logged history.",
    content: [
      { type: "p", text: "Progress is the analytics view: bodyweight trend, PR count, training volume, muscle focus, and schedule adherence — all computed from the sessions you've actually logged, never from the plan alone." },
      {
        type: "list",
        items: [
          "Overview — your at-a-glance stats for the selected period.",
          "Body — bodyweight trend, goal pace, and photos.",
          "Performance — training calendar and deeper analytics (volume trends, per-exercise stats, PR history).",
        ],
      },
      { type: "callout", text: "Progress is for trends and summaries. Train > History is where the actual day-by-day records live." },
    ],
  },

  {
    id: "nutrition",
    title: "Nutrition",
    keywords: ["nutrition", "calories", "macros", "meal plan", "diet"],
    summary: "What Nutrition covers right now.",
    content: [
      { type: "p", text: "Nutrition currently gives you a target, not a logging tool — build-out of detailed food logging is still ahead." },
      {
        type: "list",
        items: [
          "A daily calorie target",
          "Macro targets (protein/carbs/fat)",
          "A suggested meal distribution across the day",
          "A recommended meal plan with swap options",
          "General food guidance",
          "An assessment you can redo any time your goals or stats change, to recalculate your targets",
        ],
      },
      { type: "p", text: "Barcode scanning and detailed food logging aren't part of this version yet — if you don't see them, that's expected, not a bug." },
    ],
  },

  {
    id: "coach",
    title: "Coach",
    keywords: ["coach", "ai coach", "chat", "coach brief", "knowledge", "specialty"],
    summary: "What Coach actually does today.",
    content: [
      { type: "p", text: "Coach is a chat you can ask about your own training — your workouts, your progress, your nutrition targets — using the data you've actually logged in BRK." },
      {
        type: "list",
        items: [
          "Coach Brief — a short note surfaced on Today when there's something worth flagging about your recent training.",
          "Chat — ask real questions (\"How was today's workout?\", \"Am I progressing?\", \"Should I add weight?\") and get answers grounded in your logged history.",
          "Knowledge — what Coach has picked up about you so far (goals, training preferences, constraints, patterns) — reviewable and editable any time.",
          "Specialty — Coach's focus (e.g. bodybuilding vs. general training) is something you choose, and can change later.",
        ],
      },
      { type: "p", text: "Coach reads your real logged data — it's not a substitute for a human coach, and any paid or advanced AI capabilities beyond what's described here aren't active in this version." },
    ],
  },

  {
    id: "equipment",
    title: "Equipment Profiles",
    keywords: ["equipment", "machine", "profile", "cable", "gym", "default machine", "temporary machine"],
    summary: "One exercise, tracked truthfully across different machines.",
    content: [
      { type: "p", text: "An Exercise and an Equipment Profile are two different things:" },
      {
        type: "terms",
        items: [
          { term: "Exercise", def: "The movement itself — e.g. Cross Body Lat Row. It stays one exercise no matter which gym or machine you use." },
          { term: "Equipment Profile", def: "The specific physical machine you did it on — e.g. \"Life Fitness Cable\" at one gym vs. \"Matrix Cable\" at another. Save as many profiles per exercise as you actually use." },
        ],
      },
      { type: "p", text: "Why this matters: two different cable machines can feel completely different in resistance for the exact same weight number. If BRK combined their history into one line, your progression and PRs would be lying to you. Keeping profiles separate means every PR and every \"last time\" comparison is against the same real equipment." },
      { type: "p", text: "No profile picked yet? BRK treats that as the Default Machine — nothing changes for anyone who never opens the equipment selector. A one-off machine you'll never see again can be logged as a Temporary Machine — it's kept in your full history, just never used to drive PR or progression comparisons." },
      { type: "p", text: "You can switch equipment mid-exercise, even after already logging sets that session — BRK splits the entry so the sets you already did stay correctly tagged to the old machine, and the rest start fresh on the new one." },
    ],
  },

  {
    id: "recaps",
    title: "Recaps & Sharing",
    keywords: ["recap", "share", "performance", "workout recap", "full recap", "copy workout", "export"],
    summary: "Performance, Workout Recap, Minimal Story, and Full Recap — what each one is for.",
    content: [
      {
        type: "terms",
        items: [
          { term: "Performance", def: "A social-style highlight card — your best lift or PR from the session, built to post." },
          { term: "Workout Recap", def: "A shareable summary card covering every exercise, still sized for social sharing." },
          { term: "Minimal Story", def: "The sparsest option — one big number, clean and simple." },
          { term: "Full Recap", def: "Not a social card — the complete training record for that session: every exercise, every set, warm-ups, equipment, notes, and PRs. Built for you, a real coach, or pasting into an outside AI tool." },
        ],
      },
      { type: "p", text: "From Full Recap, \"Copy Workout\" copies a plain-text version of the entire session to your clipboard — paste it anywhere, including into an AI chat, for advice or analysis. \"Share Image\" makes a shareable image version of the same complete data instead." },
    ],
  },

  {
    id: "restTimer",
    title: "Rest Timer",
    keywords: ["rest timer", "timer", "rest between sets"],
    summary: "Automatic during logging, or standalone on its own.",
    content: [
      { type: "p", text: "A rest timer runs automatically between sets while you're logging a workout." },
      { type: "p", text: "Need just a timer — spotting or training someone else without logging your own workout? Train > Rest Timer opens a standalone version that works completely on its own, with no effect on your training data." },
    ],
  },

  {
    id: "bodyweight",
    title: "Bodyweight",
    keywords: ["bodyweight", "weight tracking", "trend", "body"],
    summary: "Logging and reading your weight trend.",
    content: [
      {
        type: "list",
        items: [
          "Today's quick [+] — log today's weight in one tap without leaving the home screen.",
          "Progress > Body — your full trend, rolling average, and rate of change.",
        ],
      },
      { type: "p", text: "One entry per day: logging again today updates that day's entry instead of creating a second one — the button reads \"Update entry\" once you've already logged today." },
      { type: "p", text: "A single day up or down doesn't mean much — the rolling average and weekly rate of change are what actually show whether you're trending the direction you want." },
    ],
  },

  {
    id: "dataSafety",
    title: "Data Safety",
    keywords: ["data", "backup", "export", "import", "privacy", "local storage"],
    summary: "Your data lives on this device — here's what that means.",
    content: [
      { type: "p", text: "BRK currently stores all of your training data locally on this device — there's no account and no cloud sync yet." },
      { type: "p", text: "That means switching phones, clearing your browser's site data, or uninstalling the app can lose everything unless you've backed up first." },
      { type: "p", text: "Settings has an export/import backup — export a file before switching devices, and import it to restore." },
    ],
  },

  {
    id: "faq",
    title: "FAQ / Troubleshooting",
    keywords: ["faq", "help", "troubleshooting", "questions", "problem"],
    summary: "Common questions, answered directly.",
    content: [
      {
        type: "qa",
        items: [
          { q: "Program says 3 sets. Do I have to do all 3?", a: "No. Log what you actually perform — the program is a target, your session is the real record." },
          { q: "I used another machine. Should I create another exercise?", a: "No. Keep the same exercise and change the equipment profile instead — see Equipment Profiles." },
          { q: "Can I reorder exercises?", a: "Yes, in an active workout." },
          { q: "Can I remove an exercise today?", a: "Yes. Removing it from today's session doesn't touch your saved program — it's back next time." },
          { q: "Where are my old workouts?", a: "Train > History." },
          { q: "What's the difference between Performance and Full Recap?", a: "Performance is a quick social highlight card (your best lift). Full Recap is the complete record of the session — every exercise and set — meant for you, a coach, or an outside tool, not for posting." },
        ],
      },
    ],
  },
];

export function searchHelpSections(query) {
  const q = query.trim().toLowerCase();
  if (!q) return HELP_SECTIONS;
  return HELP_SECTIONS.filter((s) => {
    if (s.title.toLowerCase().includes(q)) return true;
    if (s.summary.toLowerCase().includes(q)) return true;
    return (s.keywords || []).some((k) => k.toLowerCase().includes(q));
  });
}
