// ---------------- EQUIPMENT PROFILES ----------------
// Optional per-exercise "which physical machine did you use" context. Product principle: the
// exercise stays ONE exercise ID — Seated Leg Curl at Gym A and Seated Leg Curl at Gym B are the
// same movement with different equipment context, never two exercises. This file is purely
// additive: an athlete who never opens the equipment selector produces log entries with no
// equipmentProfileId/equipmentContext fields at all, and every function below treats that
// exactly like "Default Machine" — so existing history and every exercise nobody has profiled
// behaves byte-identical to before this feature existed.

export const MAX_PROFILES_PER_EXERCISE = 10;
// A one-off "I don't know/won't remember this machine" session — explicitly excluded from every
// direct load comparison (progression suggestions, PR detection) in both directions: it's never
// compared against prior history, and it never becomes prior history for a later comparison
// either. Preserved in full in overall exercise history/volume, just never used to drive numbers.
export const TEMPORARY_EQUIPMENT_CONTEXT = "temporary_variant";

export const DEFAULT_MACHINE_LABEL = "Default Machine";
export const TEMPORARY_MACHINE_LABEL = "Different machine (temporary)";

// Name-keyword heuristic for "is this exercise the kind where two physical units can plausibly
// produce very different loads for the same reps" — selectorized/plate-loaded machines, cables,
// Smith machines, leg presses, leg curls/extensions, hack squats, pec decks. Deliberately NOT a
// new field on every exercise-database entry (150+ existing exercises stay untouched) — BRK's
// own exercise names already consistently say "machine"/"cable"/"Smith"/etc. for anything that
// qualifies, so a name check is enough, and it's exactly the same judgment call a human would
// make reading the exercise name. Free-weight movements (barbell/dumbbell/bodyweight) never
// match, so the feature stays invisible for them per the task's explicit "remain simple by
// default" instruction.
const MACHINE_KEYWORDS = [
  "machine",
  "cable",
  "smith",
  "pulldown",
  "leg press",
  "leg curl",
  "leg extension",
  "hack squat",
  "pec deck",
  "sled",
];
export function isMachineBasedExercise(ex) {
  if (!ex?.name) return false;
  const n = ex.name.toLowerCase();
  return MACHINE_KEYWORDS.some((k) => n.includes(k));
}

export function sanitizeEquipmentProfiles(raw) {
  if (!Array.isArray(raw)) return [];
  return raw.filter(
    (p) => p && typeof p === "object" && typeof p.id === "string" && typeof p.exerciseId === "string" && typeof p.label === "string" && p.label.trim()
  );
}

export function profilesForExercise(state, exId) {
  return sanitizeEquipmentProfiles(state?.equipmentProfiles).filter((p) => p.exerciseId === exId);
}

// Pure: returns the NEW equipmentProfiles array (caller writes it via updateState). `id` can be
// pre-generated by the caller (e.g. so it can immediately select the new profile without relying
// on reading the value back out of a state updater) or left to be generated here.
export function addEquipmentProfile(state, exId, label, gymLabel, id = null) {
  const existing = sanitizeEquipmentProfiles(state?.equipmentProfiles);
  const trimmedLabel = (label || "").trim();
  if (!trimmedLabel) return existing;
  const forEx = existing.filter((p) => p.exerciseId === exId);
  if (forEx.length >= MAX_PROFILES_PER_EXERCISE) return existing;
  const profile = {
    id: id || `equipment_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`,
    exerciseId: exId,
    label: trimmedLabel,
    gymLabel: (gymLabel || "").trim() || null,
    isDefault: false,
    createdAt: new Date().toISOString(),
  };
  return [...existing, profile];
}

// Manual only (task: "Do NOT automatically switch profile based on GPS/location — keep it
// manual and reliable") — exactly one profile per exercise can be marked "usual."
export function setDefaultEquipmentProfile(state, exId, profileId) {
  const existing = sanitizeEquipmentProfiles(state?.equipmentProfiles);
  return existing.map((p) => (p.exerciseId === exId ? { ...p, isDefault: p.id === profileId } : p));
}

export function resolveEquipmentProfile(state, profileId) {
  if (!profileId) return null;
  return sanitizeEquipmentProfiles(state?.equipmentProfiles).find((p) => p.id === profileId) || null;
}

export function defaultProfileFor(state, exId) {
  return profilesForExercise(state, exId).find((p) => p.isDefault) || null;
}

// "Save this machine profile" (task section 17) — turns a just-logged temporary-variant entry
// into real history under a newly-saved profile, instead of leaving it permanently isolated.
export function convertTemporaryLogToProfile(logs, logId, profileId) {
  return (logs || []).map((l) => (l.id === logId ? { ...l, equipmentProfileId: profileId, equipmentContext: null } : l));
}

export function equipmentDisplayLabel(state, equipmentProfileId, equipmentContext) {
  if (equipmentContext === TEMPORARY_EQUIPMENT_CONTEXT) return TEMPORARY_MACHINE_LABEL;
  if (!equipmentProfileId) return DEFAULT_MACHINE_LABEL;
  const profile = resolveEquipmentProfile(state, equipmentProfileId);
  // An orphaned id (its profile was somehow removed) falls back safely rather than showing
  // "undefined" — this app currently has no delete affordance, so this is a defensive-only path.
  return profile ? profile.label : DEFAULT_MACHINE_LABEL;
}

// Two log entries are directly load-comparable only when they share the same equipment bucket:
// the same saved profile, or both "Default Machine" (no profile selected at all — this is why an
// athlete who never touches this feature sees zero behavior change, since every one of their
// entries shares the same null bucket). A temporary-variant entry NEVER matches anything,
// including another temporary entry from a different session — each one-off session is an
// isolated data point, never a machine BRK has reason to believe is the same as any other.
export function sameEquipmentBucket(entry, targetProfileId, targetContext) {
  if (targetContext === TEMPORARY_EQUIPMENT_CONTEXT) return false;
  if (entry?.equipmentContext === TEMPORARY_EQUIPMENT_CONTEXT) return false;
  return (entry?.equipmentProfileId || null) === (targetProfileId || null);
}
